In [4]:
import pandas as pd

In [5]:
patients = pd.read_csv('C:/Users/HELLO/OneDrive/Desktop/EHR_Cleaning_Prototype/DATASETS/raw/patients.csv' , sep="\t")
patients.head(1)

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,69af9fdb-6026-cf15-8110-60645be1a286,1/15/1951,NaN,999-83-1923,S99995838,X13314221X,Mrs.,Sasha806,Ashlie138,Stamm704,...,Uxbridge,Massachusetts,Worcester County,NaN,0,42.048896,-71.644746,781858.42,182267.18,53813

In [6]:
patients.shape

(111, 28)

In [7]:
patients.columns
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   111 non-null    str
 1   BIRTHDATE            111 non-null    str
 2   DEATHDATE            13 non-null     str
 3   SSN                  111 non-null    str
 4   DRIVERS              96 non-null     str
 5   PASSPORT             92 non-null     str
 6   PREFIX               93 non-null     str
 7   FIRST                111 non-null    str
 8   MIDDLE               85 non-null     str
 9   LAST                 111 non-null    str
 10  SUFFIX               3 non-null      str
 11  MAIDEN               40 non-null     str
 12  MARITAL              86 non-null     str
 13  RACE                 111 non-null    str
 14  ETHNICITY            111 non-null    str
 15  GENDER               111 non-null    str
 16  BIRTHPLACE           111 non-null    str
 17  ADDRESS              111 non-null    str
 18  CITY                 111 non-null    str
 19  STATE                111 non-null    str
 20  COUNTY               111 non-null    str
 21  FIPS                 84 non-null     float64
 22  ZIP                  111 non-null    int64
 23  LAT                  111 non-null    float64
 24  LON                  111 non-null    float64
 25  HEALTHCARE_EXPENSES  111 non-null    float64
 26  HEALTHCARE_COVERAGE  111 non-null    float64
 27  INCOME               111 non-null    int64
dtypes: float64(5), int64(2), str(21)
memory usage: 24.4 KB

In [8]:
patients.isnull().sum()

Id                       0
BIRTHDATE                0
DEATHDATE               98
SSN                      0
DRIVERS                 15
PASSPORT                19
PREFIX                  18
FIRST                    0
MIDDLE                  26
LAST                     0
SUFFIX                 108
MAIDEN                  71
MARITAL                 25
RACE                     0
ETHNICITY                0
GENDER                   0
BIRTHPLACE               0
ADDRESS                  0
CITY                     0
STATE                    0
COUNTY                   0
FIPS                    27
ZIP                      0
LAT                      0
LON                      0
HEALTHCARE_EXPENSES      0
HEALTHCARE_COVERAGE      0
INCOME                   0
dtype: int64

In [9]:
patients.columns.values

<StringArray>
[                 'Id',           'BIRTHDATE',           'DEATHDATE',
                 'SSN',             'DRIVERS',            'PASSPORT',
              'PREFIX',               'FIRST',              'MIDDLE',
                'LAST',              'SUFFIX',              'MAIDEN',
             'MARITAL',                'RACE',           'ETHNICITY',
              'GENDER',          'BIRTHPLACE',             'ADDRESS',
                'CITY',               'STATE',              'COUNTY',
                'FIPS',                 'ZIP',                 'LAT',
                 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE',
              'INCOME']
Length: 28, dtype: str

In [10]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   111 non-null    str
 1   BIRTHDATE            111 non-null    str
 2   DEATHDATE            13 non-null     str
 3   SSN                  111 non-null    str
 4   DRIVERS              96 non-null     str
 5   PASSPORT             92 non-null     str
 6   PREFIX               93 non-null     str
 7   FIRST                111 non-null    str
 8   MIDDLE               85 non-null     str
 9   LAST                 111 non-null    str
 10  SUFFIX               3 non-null      str
 11  MAIDEN               40 non-null     str
 12  MARITAL              86 non-null     str
 13  RACE                 111 non-null    str
 14  ETHNICITY            111 non-null    str
 15  GENDER               111 non-null    str
 16  BIRTHPLACE           111 non-null    str
 17  ADDRESS              111 non-null    str
 18  CITY                 111 non-null    str
 19  STATE                111 non-null    str
 20  COUNTY               111 non-null    str
 21  FIPS                 84 non-null     float64
 22  ZIP                  111 non-null    int64
 23  LAT                  111 non-null    float64
 24  LON                  111 non-null    float64
 25  HEALTHCARE_EXPENSES  111 non-null    float64
 26  HEALTHCARE_COVERAGE  111 non-null    float64
 27  INCOME               111 non-null    int64
dtypes: float64(5), int64(2), str(21)
memory usage: 24.4 KB

In [11]:
patients.head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,69af9fdb-6026-cf15-8110-60645be1a286,1/15/1951,NaN,999-83-1923,S99995838,X13314221X,Mrs.,Sasha806,Ashlie138,Stamm704,...,Uxbridge,Massachusetts,Worcester County,NaN,0,42.048896,-71.644746,781858.42,182267.18,53813
1,e2b7d298-e3e5-8e5a-804c-a8342fdeb164,10/27/1957,NaN,999-52-6475,S99916774,X60183820X,Mrs.,Shawnta32,Janeth814,Hintz995,...,Danvers,Massachusetts,Essex County,25009.0,1937,42.550276,-70.987312,617728.28,860065.14,109027
2,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,12/4/2005,NaN,999-56-6377,S99960468,X16189809X,Ms.,Haley279,Deandra603,Ondricka197,...,Fitchburg,Massachusetts,Worcester County,25027.0,1420,42.585057,-71.835094,11148.62,726893.50,125882
3,36a8268b-0e08-f9d6-6999-eca371aab83c,5/14/1978,NaN,999-53-1726,S99981580,X20024386X,Mrs.,Jung484,Valorie864,Stehr398,...,Somerville,Massachusetts,Middlesex County,25017.0,2144,42.399046,-71.132572,739328.17,135123.90,65255
4,7bfad7bf-fbc0-2a68-6c37-b9351c1ec651,9/9/2013,NaN,999-75-1410,NaN,NaN,NaN,Romona686,Jenine75,Cruickshank494,...,Ipswich,Massachusetts,Essex County,25009.0,1938,42.653922,-70.883568,17836.60,13403.05,136314

In [12]:
conditions = pd.read_csv('C:/Users/HELLO/OneDrive/Desktop/EHR_Cleaning_Prototype/DATASETS/raw/conditions.csv' , sep="\t")
conditions.head(5)

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION
0,3/10/1969,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-5a00-372c84c0e4fa,http://snomed.info/sct,224299000.0,Received higher education (finding)
1,1/25/1993,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-1cb6-f99e68e93176,http://snomed.info/sct,162864005.0,Body mass index 30+ - obesity (finding)
2,1/15/2001,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-329f-6dbe9af1a8b4,http://snomed.info/sct,714628002.0,Prediabetes (finding)
3,1/15/2001,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-329f-6dbe9af1a8b4,http://snomed.info/sct,271737000.0,Anemia (disorder)
4,12/9/1973,NaN,e2b7d298-e3e5-8e5a-804c-a8342fdeb164,e2b7d298-e3e5-8e5a-c8d2-10b464f4ec42,http://snomed.info/sct,160968000.0,Risk activity involvement (finding)

In [13]:
conditions.shape

(3817, 7)

In [14]:
conditions.columns

Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE',
       'DESCRIPTION'],
      dtype='str')

In [15]:
conditions.info()

<class 'pandas.DataFrame'>
RangeIndex: 3817 entries, 0 to 3816
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START        3817 non-null   str
 1   STOP         2712 non-null   str
 2   PATIENT      3817 non-null   str
 3   ENCOUNTER    3817 non-null   str
 4   SYSTEM       3817 non-null   str
 5   CODE         3817 non-null   float64
 6   DESCRIPTION  3817 non-null   str
dtypes: float64(1), str(6)
memory usage: 208.9 KB

In [16]:
conditions.isnull()

      START   STOP  PATIENT  ENCOUNTER  SYSTEM   CODE  DESCRIPTION
0     False   True    False      False   False  False        False
1     False   True    False      False   False  False        False
2     False   True    False      False   False  False        False
3     False   True    False      False   False  False        False
4     False   True    False      False   False  False        False
...     ...    ...      ...        ...     ...    ...          ...
3812  False   True    False      False   False  False        False
3813  False   True    False      False   False  False        False
3814  False  False    False      False   False  False        False
3815  False  False    False      False   False  False        False
3816  False   True    False      False   False  False        False

[3817 rows x 7 columns]

In [17]:
conditions.describe

<bound method NDFrame.describe of            START       STOP                               PATIENT  \
0      3/10/1969        NaN  69af9fdb-6026-cf15-8110-60645be1a286
1      1/25/1993        NaN  69af9fdb-6026-cf15-8110-60645be1a286
2      1/15/2001        NaN  69af9fdb-6026-cf15-8110-60645be1a286
3      1/15/2001        NaN  69af9fdb-6026-cf15-8110-60645be1a286
4      12/9/1973        NaN  e2b7d298-e3e5-8e5a-804c-a8342fdeb164
...          ...        ...                                   ...
3812  10/10/2023        NaN  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
3813   10/3/2024        NaN  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
3814   10/3/2024  10/9/2025  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
3815   10/3/2024  10/9/2025  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
3816   10/9/2025        NaN  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8

                                 ENCOUNTER                  SYSTEM  \
0     69af9fdb-6026-cf15-5a00-372c84c0e4fa  http://snomed.info/sct
1     69af9fdb-6026-cf15-1cb6-f99e68e93176  http://snomed.info/sct
2     69af9fdb-6026-cf15-329f-6dbe9af1a8b4  http://snomed.info/sct
3     69af9fdb-6026-cf15-329f-6dbe9af1a8b4  http://snomed.info/sct
4     e2b7d298-e3e5-8e5a-c8d2-10b464f4ec42  http://snomed.info/sct
...                                    ...                     ...
3812  d6fc4f34-d0ac-a09b-e9b6-30c2560ccea2  http://snomed.info/sct
3813  d6fc4f34-d0ac-a09b-b175-7ec2469b2376  http://snomed.info/sct
3814  d6fc4f34-d0ac-a09b-b175-7ec2469b2376  http://snomed.info/sct
3815  d6fc4f34-d0ac-a09b-b175-7ec2469b2376  http://snomed.info/sct
3816  d6fc4f34-d0ac-a09b-49ab-63a93726f03a  http://snomed.info/sct

             CODE                                        DESCRIPTION
0     224299000.0                Received higher education (finding)
1     162864005.0            Body mass index 30+ - obesity (finding)
2     714628002.0                              Prediabetes (finding)
3     271737000.0                                  Anemia (disorder)
4     160968000.0                Risk activity involvement (finding)
...           ...                                                ...
3812  274531002.0  Abnormal findings diagnostic imaging heart+cor...
3813  314529007.0                  Medication review due (situation)
3814  160904001.0                     Part-time employment (finding)
3815   73595000.0                                   Stress (finding)
3816  160903007.0                     Full-time employment (finding)

[3817 rows x 7 columns]>

In [18]:
observations = pd.read_csv('C:/Users/HELLO/OneDrive/Desktop/EHR_Cleaning_Prototype/DATASETS/raw/observations.csv' , sep="\t")
observations.head(5)

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE
0,2016-09-14T14:14:37Z,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-1ec6-f421cd754275,vital-signs,8310-5,Body temperature,37.2,Cel,numeric
1,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,8302-2,Body Height,144.8,cm,numeric
2,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,4,{score},numeric
3,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,29463-7,Body Weight,40.2,kg,numeric
4,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,39156-5,Body mass index (BMI) [Ratio],19.2,kg/m2,numeric

In [19]:
observations.shape

(72372, 9)

In [20]:
observations.columns

Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION',
       'VALUE', 'UNITS', 'TYPE'],
      dtype='str')

In [21]:
observations.describe

<bound method NDFrame.describe of                        DATE                               PATIENT  \
0      2016-09-14T14:14:37Z  69af9fdb-6026-cf15-8110-60645be1a286
1      2016-12-18T18:43:43Z  ca4f2fef-0fea-5cdb-314c-9d6689cfabb0
2      2016-12-18T18:43:43Z  ca4f2fef-0fea-5cdb-314c-9d6689cfabb0
3      2016-12-18T18:43:43Z  ca4f2fef-0fea-5cdb-314c-9d6689cfabb0
4      2016-12-18T18:43:43Z  ca4f2fef-0fea-5cdb-314c-9d6689cfabb0
...                     ...                                   ...
72367  2022-04-28T05:14:17Z  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
72368  2023-04-28T05:14:17Z  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
72369  2024-04-28T05:14:17Z  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
72370  2025-04-28T05:14:17Z  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8
72371  2026-04-28T05:14:17Z  d6fc4f34-d0ac-a09b-94e4-01fc4a44d3a8

                                  ENCOUNTER     CATEGORY     CODE  \
0      69af9fdb-6026-cf15-1ec6-f421cd754275  vital-signs   8310-5
1      ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs   8302-2
2      ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs  72514-3
3      ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs  29463-7
4      ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs  39156-5
...                                     ...          ...      ...
72367                                   NaN          NaN     QOLS
72368                                   NaN          NaN     QOLS
72369                                   NaN          NaN     QOLS
72370                                   NaN          NaN     QOLS
72371                                   NaN          NaN     QOLS

                                             DESCRIPTION  VALUE    UNITS  \
0                                       Body temperature   37.2      Cel
1                                            Body Height  144.8       cm
2      Pain severity - 0-10 verbal numeric rating [Sc...      4  {score}
3                                            Body Weight   40.2       kg
4                          Body mass index (BMI) [Ratio]   19.2    kg/m2
...                                                  ...    ...      ...
72367                                               QOLS      1  {score}
72368                                               QOLS      1  {score}
72369                                               QOLS      1  {score}
72370                                               QOLS    0.9  {score}
72371                                               QOLS    0.9  {score}

          TYPE
0      numeric
1      numeric
2      numeric
3      numeric
4      numeric
...        ...
72367  numeric
72368  numeric
72369  numeric
72370  numeric
72371  numeric

[72372 rows x 9 columns]>

In [22]:
observations.info()

<class 'pandas.DataFrame'>
RangeIndex: 72372 entries, 0 to 72371
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         72372 non-null  str
 1   PATIENT      72372 non-null  str
 2   ENCOUNTER    69321 non-null  str
 3   CATEGORY     69321 non-null  str
 4   CODE         72372 non-null  str
 5   DESCRIPTION  72372 non-null  str
 6   VALUE        72372 non-null  str
 7   UNITS        51813 non-null  str
 8   TYPE         72372 non-null  str
dtypes: str(9)
memory usage: 5.0 MB

In [23]:
rows, cols = patients.shape

In [24]:
columns = patients.columns.tolist()
columns

['Id',
 'BIRTHDATE',
 'DEATHDATE',
 'SSN',
 'DRIVERS',
 'PASSPORT',
 'PREFIX',
 'FIRST',
 'MIDDLE',
 'LAST',
 'SUFFIX',
 'MAIDEN',
 'MARITAL',
 'RACE',
 'ETHNICITY',
 'GENDER',
 'BIRTHPLACE',
 'ADDRESS',
 'CITY',
 'STATE',
 'COUNTY',
 'FIPS',
 'ZIP',
 'LAT',
 'LON',
 'HEALTHCARE_EXPENSES',
 'HEALTHCARE_COVERAGE',
 'INCOME']

In [25]:
numerical_columns = patients.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_columns

['FIPS',
 'ZIP',
 'LAT',
 'LON',
 'HEALTHCARE_EXPENSES',
 'HEALTHCARE_COVERAGE',
 'INCOME']

In [26]:
categorical_columns = patients.select_dtypes(include=['object']).columns.tolist()
categorical_columns

C:\Users\HELLO\AppData\Local\Temp\ipykernel_5404\3177216540.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = patients.select_dtypes(include=['object']).columns.tolist()

['Id',
 'BIRTHDATE',
 'DEATHDATE',
 'SSN',
 'DRIVERS',
 'PASSPORT',
 'PREFIX',
 'FIRST',
 'MIDDLE',
 'LAST',
 'SUFFIX',
 'MAIDEN',
 'MARITAL',
 'RACE',
 'ETHNICITY',
 'GENDER',
 'BIRTHPLACE',
 'ADDRESS',
 'CITY',
 'STATE',
 'COUNTY']

In [27]:
missing_values = patients.isnull().sum()
missing_values

Id                       0
BIRTHDATE                0
DEATHDATE               98
SSN                      0
DRIVERS                 15
PASSPORT                19
PREFIX                  18
FIRST                    0
MIDDLE                  26
LAST                     0
SUFFIX                 108
MAIDEN                  71
MARITAL                 25
RACE                     0
ETHNICITY                0
GENDER                   0
BIRTHPLACE               0
ADDRESS                  0
CITY                     0
STATE                    0
COUNTY                   0
FIPS                    27
ZIP                      0
LAT                      0
LON                      0
HEALTHCARE_EXPENSES      0
HEALTHCARE_COVERAGE      0
INCOME                   0
dtype: int64

In [28]:
duplicates = patients.duplicated().sum()
duplicates

np.int64(0)

In [29]:
memory = patients.memory_usage(deep=True).sum()/1024**2
#memory in megabytes

In [30]:
def profile_dataset(patients):
    print(f"Dataset shape: {patients.shape}")
    print(f"Dataset memory usage: {memory:.2f} MB")
    print(f"Number of missing values: {missing_values.sum()}")
    print(f"Number of duplicates: {duplicates}")
    print(f"Numerical columns: {numerical_columns}")
    print(f"Categorical columns: {categorical_columns}")
    print(f"Missing values per column: \n{missing_values}")
    print(f"Duplicates per column: \n{patients.duplicated().sum()}")

In [31]:
profile_dataset(patients)

Dataset shape: (111, 28)
Dataset memory usage: 0.13 MB
Number of missing values: 407
Number of duplicates: 0
Numerical columns: ['FIPS', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME']
Categorical columns: ['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'MIDDLE', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY']
Missing values per column:
Id                       0
BIRTHDATE                0
DEATHDATE               98
SSN                      0
DRIVERS                 15
PASSPORT                19
PREFIX                  18
FIRST                    0
MIDDLE                  26
LAST                     0
SUFFIX                 108
MAIDEN                  71
MARITAL                 25
RACE                     0
ETHNICITY                0
GENDER                   0
BIRTHPLACE               0
ADDRESS                  0
CITY                     0
STATE                    0
COUNTY                   0
FIPS                    27
ZIP                      0
LAT                      0
LON                      0
HEALTHCARE_EXPENSES      0
HEALTHCARE_COVERAGE      0
INCOME                   0
dtype: int64
Duplicates per column:
0

In [32]:
%whos

Variable              Type         Data/Info
--------------------------------------------
categorical_columns   list         n=21
cols                  int          28
columns               list         n=28
conditions            DataFrame    Shape: (3817, 7)
duplicates            int64        0
evaluate_pipeline     function     <function evaluate_pipeli<...>ne at 0x0000018C3520EC40>
memory                float64      0.13077735900878906
missing_values        Series       Shape: (28,)
numerical_columns     list         n=7
observations          DataFrame    Shape: (72372, 9)
patients              DataFrame    Shape: (111, 28)
pd                    module       <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
profile_dataset       function     <function profile_dataset at 0x0000018C4D668CA0>
rows                  int          111

In [33]:
rows,columns = conditions.shape
columns = conditions.columns.tolist()
columns
numerical_columns = conditions.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_columns
categorical_columns = conditions.select_dtypes(include=['object']).columns.tolist()
categorical_columns
missing_values = conditions.isnull().sum()
missing_values
duplicates = conditions.duplicated().sum()
duplicates

C:\Users\HELLO\AppData\Local\Temp\ipykernel_5404\2445496025.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = conditions.select_dtypes(include=['object']).columns.tolist()

np.int64(0)

In [34]:
def profile_dataset(conditions):
    print(f"Dataset shape: {conditions.shape}")
    print(f"Numerical columns: {numerical_columns}")
    print(f"Categorical columns: {categorical_columns}")
    print(f"Missing values per column: \n{missing_values}")
    print(f"Duplicates per column: \n{conditions.duplicated().sum()}")
profile_dataset(conditions)

Dataset shape: (3817, 7)
Numerical columns: ['CODE']
Categorical columns: ['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'DESCRIPTION']
Missing values per column:
START             0
STOP           1105
PATIENT           0
ENCOUNTER         0
SYSTEM            0
CODE              0
DESCRIPTION       0
dtype: int64
Duplicates per column:
0

In [35]:
rows,columns = observations.shape
columns = observations.columns.tolist()
columns
numerical_columns = observations.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_columns
categorical_columns = observations.select_dtypes(include=['object']).columns.tolist()
categorical_columns
missing_values = observations.isnull().sum()
missing_values
duplicates = observations.duplicated().sum()
duplicates
def profile_dataset(observations):
    print(f"Dataset shape: {observations.shape}")
    print(f"Numerical columns: {numerical_columns}")
    print(f"Categorical columns: {categorical_columns}")
    print(f"Missing values per column: \n{missing_values}")
    print(f"Duplicates per column: \n{observations.duplicated().sum()}")
profile_dataset(observations)

C:\Users\HELLO\AppData\Local\Temp\ipykernel_5404\2809742108.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = observations.select_dtypes(include=['object']).columns.tolist()

Dataset shape: (72372, 9)
Numerical columns: []
Categorical columns: ['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']
Missing values per column:
DATE               0
PATIENT            0
ENCOUNTER       3051
CATEGORY        3051
CODE               0
DESCRIPTION        0
VALUE              0
UNITS          20559
TYPE               0
dtype: int64
Duplicates per column:
7

In [36]:
print(missing_values)

DATE               0
PATIENT            0
ENCOUNTER       3051
CATEGORY        3051
CODE               0
DESCRIPTION        0
VALUE              0
UNITS          20559
TYPE               0
dtype: int64

In [37]:
missing_cols = observations.columns[observations.isnull().any()].tolist()
print(missing_cols)

['ENCOUNTER', 'CATEGORY', 'UNITS']

In [38]:
observations[missing_cols].dtypes

ENCOUNTER    str
CATEGORY     str
UNITS        str
dtype: object

In [39]:
from sklearn.impute import SimpleImputer

In [40]:
mode_imputer = SimpleImputer(strategy='most_frequent')

mode_observations = observations.copy()
mode_observations[missing_cols] = mode_imputer.fit_transform(mode_observations[missing_cols])

In [41]:
mode_observations[['ENCOUNTER' , 'CATEGORY','UNITS']].head()

                              ENCOUNTER     CATEGORY    UNITS
0  69af9fdb-6026-cf15-1ec6-f421cd754275  vital-signs      Cel
1  ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs       cm
2  ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs  {score}
3  ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs       kg
4  ca4f2fef-0fea-5cdb-8256-7d69c050f533  vital-signs    kg/m2

In [42]:
id_cols = ['ENCOUNTER']
other_cols = ['CATEGORY', 'UNITS']

In [43]:
mode_imputer = SimpleImputer(strategy='most_frequent')

observations[other_cols] = mode_imputer.fit_transform(
    observations[other_cols]
)

In [44]:
observations = observations.dropna(subset=['ENCOUNTER'])

In [45]:
observations['ENCOUNTER'] = observations['ENCOUNTER'].fillna('UNKNOWN')

In [46]:
observations[['ENCOUNTER' , 'CATEGORY','UNITS']].head(40)

                               ENCOUNTER        CATEGORY    UNITS
0   69af9fdb-6026-cf15-1ec6-f421cd754275     vital-signs      Cel
1   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs       cm
2   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs  {score}
3   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs       kg
4   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs    kg/m2
5   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs        %
6   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs   mm[Hg]
7   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs   mm[Hg]
8   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs     /min
9   ca4f2fef-0fea-5cdb-8256-7d69c050f533     vital-signs     /min
10  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory  10*3/uL
11  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory  10*6/uL
12  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory     g/dL
13  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory        %
14  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory       fL
15  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory       pg
16  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory     g/dL
17  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory       fL
18  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory  10*3/uL
19  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory       fL
20  ca4f2fef-0fea-5cdb-8256-7d69c050f533      laboratory       fL
21  ca4f2fef-0fea-5cdb-8256-7d69c050f533  social-history    mg/dL
22  ca4f2fef-0fea-5cdb-92ba-1db4b8aa72e3     vital-signs      Cel
23  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs       cm
24  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs  {score}
25  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs       kg
26  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs    kg/m2
27  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs        %
28  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs   mm[Hg]
29  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs   mm[Hg]
30  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs     /min
31  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b     vital-signs     /min
32  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b  social-history    mg/dL
33  e2b7d298-e3e5-8e5a-0cf3-d30e0df98c42      laboratory        %
34  ca4f2fef-0fea-5cdb-156a-6e8a1d1c0d5b          survey  {score}
35  e2b7d298-e3e5-8e5a-0cf3-d30e0df98c42     vital-signs       cm
36  e2b7d298-e3e5-8e5a-0cf3-d30e0df98c42     vital-signs  {score}
37  e2b7d298-e3e5-8e5a-0cf3-d30e0df98c42     vital-signs       kg
38  e2b7d298-e3e5-8e5a-0cf3-d30e0df98c42     vital-signs    kg/m2
39  69af9fdb-6026-cf15-4ddb-6fb2bb672096      laboratory  10*3/uL

In [47]:
mode_observations[['ENCOUNTER','CATEGORY','UNITS']].isnull().sum()

ENCOUNTER    0
CATEGORY     0
UNITS        0
dtype: int64

In [48]:
#Constant  imputer
constant_imputer = SimpleImputer(
    strategy='constant',
    fill_value='Unknown'
)

In [49]:
constant_observations = observations.copy()

In [50]:
constant_observations[missing_cols] = constant_imputer.fit_transform(
    constant_observations[missing_cols]
)

In [51]:
constant_observations[missing_cols].isnull().sum()

ENCOUNTER    0
CATEGORY     0
UNITS        0
dtype: int64

In [52]:
observations['UNITS'].isnull().sum()

np.int64(0)

In [53]:
mode_observations.shape
constant_observations.shape

(69321, 9)

outlier engine

In [54]:
mode_observations.dtypes

DATE           str
PATIENT        str
ENCOUNTER      str
CATEGORY       str
CODE           str
DESCRIPTION    str
VALUE          str
UNITS          str
TYPE           str
dtype: object

#convert it into numeric from str

In [55]:
mode_observations['VALUE_NUMERIC'] = pd.to_numeric(
    mode_observations['VALUE'],
    errors='coerce'
)

In [56]:
mode_observations['VALUE_NUMERIC'].head(100)

0      37.2
1     144.8
2       4.0
3      40.2
4      19.2
      ...
95     27.6
96      0.2
97      0.0
98      0.0
99      0.1
Name: VALUE_NUMERIC, Length: 100, dtype: float64

In [57]:
has_string = mode_observations['UNITS'].apply(lambda x: isinstance(x, str)).any()

print(has_string)

True

In [58]:
mode_observations['VALUE_NUMERIC'].dtypes

dtype('float64')

In [59]:
numeric_observations = mode_observations.dropna(subset=['VALUE_NUMERIC'])

In [60]:
numeric_observations.head()

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE,VALUE_NUMERIC
0,2016-09-14T14:14:37Z,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-1ec6-f421cd754275,vital-signs,8310-5,Body temperature,37.2,Cel,numeric,37.2
1,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,8302-2,Body Height,144.8,cm,numeric,144.8
2,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,4,{score},numeric,4.0
3,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,29463-7,Body Weight,40.2,kg,numeric,40.2
4,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,39156-5,Body mass index (BMI) [Ratio],19.2,kg/m2,numeric,19.2

In [61]:
numeric_observations.shape

(46402, 10)

In [62]:
numeric_df = mode_observations.dropna(subset=['VALUE_NUMERIC'])

numeric_observations.shape

numeric_observations.head()

numeric_observations['VALUE_NUMERIC'].dtype

dtype('float64')

IQR Outlier Detection

In [63]:
numeric_observations.select_dtypes(include=['float64','int64']).columns

Index(['VALUE_NUMERIC'], dtype='str')

In [64]:
col = 'VALUE_NUMERIC'

In [65]:
Q1 = numeric_observations[col].quantile(0.25)

Q3 = numeric_observations[col].quantile(0.75)

IQR = Q3-Q1

In [66]:
print(Q1)
print(Q3)
print(IQR)

4.0
87.0
83.0

In [67]:
lower_bound = Q1 - 1.5 * IQR

In [68]:
upper_bound = Q3 + 1.5 * IQR

In [69]:
print(lower_bound)
print(upper_bound)

-120.5
211.5

In [70]:
outliers = numeric_observations[
    (numeric_observations['VALUE_NUMERIC'] < lower_bound)
    |
    (numeric_observations['VALUE_NUMERIC'] > upper_bound)
]

In [71]:
print(len(outliers))

2244

In [72]:
outliers[['DESCRIPTION','VALUE_NUMERIC']].head(20)

                                           DESCRIPTION  VALUE_NUMERIC
18    Platelets [#/volume] in Blood by Automated count          381.2
19   Platelet distribution width [Entitic volume] i...          271.3
48    Platelets [#/volume] in Blood by Automated count          349.6
49   Platelet distribution width [Entitic volume] i...          516.2
62        Cholesterol [Mass/volume] in Serum or Plasma          303.7
64   Cholesterol in LDL [Mass/volume] in Serum or P...          227.1
75   What was your best estimate of the total incom...       109027.0
132  What was your best estimate of the total incom...       109027.0
183  What was your best estimate of the total incom...        53813.0
234  What was your best estimate of the total incom...       109027.0
251   Platelets [#/volume] in Blood by Automated count          446.3
252  Platelet distribution width [Entitic volume] i...          486.7
262   Platelets [#/volume] in Blood by Automated count          382.0
263  Platelet distribution width [Entitic volume] i...          326.5
273   Platelets [#/volume] in Blood by Automated count          445.5
274  Platelet distribution width [Entitic volume] i...          447.9
284   Platelets [#/volume] in Blood by Automated count          426.8
285  Platelet distribution width [Entitic volume] i...          471.9
325  What was your best estimate of the total incom...       109027.0
366   Platelets [#/volume] in Blood by Automated count          224.3

In [73]:
outliers[['DESCRIPTION','VALUE','VALUE_NUMERIC']].head(20)

                                           DESCRIPTION   VALUE  VALUE_NUMERIC
18    Platelets [#/volume] in Blood by Automated count   381.2          381.2
19   Platelet distribution width [Entitic volume] i...   271.3          271.3
48    Platelets [#/volume] in Blood by Automated count   349.6          349.6
49   Platelet distribution width [Entitic volume] i...   516.2          516.2
62        Cholesterol [Mass/volume] in Serum or Plasma   303.7          303.7
64   Cholesterol in LDL [Mass/volume] in Serum or P...   227.1          227.1
75   What was your best estimate of the total incom...  109027       109027.0
132  What was your best estimate of the total incom...  109027       109027.0
183  What was your best estimate of the total incom...   53813        53813.0
234  What was your best estimate of the total incom...  109027       109027.0
251   Platelets [#/volume] in Blood by Automated count   446.3          446.3
252  Platelet distribution width [Entitic volume] i...   486.7          486.7
262   Platelets [#/volume] in Blood by Automated count     382          382.0
263  Platelet distribution width [Entitic volume] i...   326.5          326.5
273   Platelets [#/volume] in Blood by Automated count   445.5          445.5
274  Platelet distribution width [Entitic volume] i...   447.9          447.9
284   Platelets [#/volume] in Blood by Automated count   426.8          426.8
285  Platelet distribution width [Entitic volume] i...   471.9          471.9
325  What was your best estimate of the total incom...  109027       109027.0
366   Platelets [#/volume] in Blood by Automated count   224.3          224.3

In [74]:
from sklearn.ensemble import IsolationForest

In [75]:
iso = IsolationForest(
    contamination=0.05,
    random_state=42
)

In [76]:
numeric_observations['IF_Outlier'] = iso.fit_predict(
    numeric_observations[['VALUE_NUMERIC']]
    
)

In [77]:
numeric_observations['IF_Outlier']

0        1
1        1
2        1
3        1
4        1
        ..
72367    1
72368    1
72369    1
72370    1
72371    1
Name: IF_Outlier, Length: 46402, dtype: int64

In [78]:
if_outliers = numeric_observations[
    numeric_observations['IF_Outlier']==-1
]

In [79]:
print(len(if_outliers))

2319

In [80]:
(len(outliers))

2244

In [81]:
def detect_outliers(observations):
    {
'IQR Outliers': len(outliers),
'Isolation Forest Outliers': len(if_outliers)
}

In [82]:
keep_observations = numeric_observations.copy()

In [83]:
iqr_observations = numeric_observations[
    (numeric_observations['VALUE_NUMERIC'] >= lower_bound)
    &
    (numeric_observations['VALUE_NUMERIC'] <= upper_bound)
]

In [84]:
if_observations = numeric_observations[
    numeric_observations['IF_Outlier']==1
]

(len(if_observations))

44083

In [85]:
#SCALLING ENGINE
from sklearn.preprocessing import StandardScaler

In [86]:
standard_scaler = StandardScaler()

In [87]:
keep_standard_observations = keep_observations.copy()

In [88]:
keep_standard_observations['VALUE_NUMERIC'] = standard_scaler.fit_transform(
    keep_standard_observations[['VALUE_NUMERIC']]
)

In [89]:
keep_standard_observations['VALUE_NUMERIC'].describe()

count    4.640200e+04
mean    -7.656380e-18
std      1.000011e+00
min     -8.864973e-02
25%     -8.844072e-02
50%     -8.798926e-02
75%     -8.612769e-02
max      2.500809e+01
Name: VALUE_NUMERIC, dtype: float64

In [90]:
from sklearn.preprocessing import RobustScaler

In [91]:
robust_scaler = RobustScaler()

In [92]:
keep_robust_observations = keep_observations.copy()

In [93]:
keep_robust_observations['VALUE_NUMERIC'] = robust_scaler.fit_transform(
    keep_robust_observations[['VALUE_NUMERIC']]
)

In [94]:
keep_robust_observations['VALUE_NUMERIC'].describe()

count    46402.000000
mean        38.040619
std        432.337180
min         -0.285542
25%         -0.195181
50%          0.000000
75%          0.804819
max      10849.853012
Name: VALUE_NUMERIC, dtype: float64

In [95]:

def scale_data(observations, method='standard'):

    scaled_observations = observations.copy()

    if method == 'standard':

        scaler = StandardScaler()

    elif method == 'robust':

        scaler = RobustScaler()
    scaled_observations['VALUE_NUMERIC'] = scaler.fit_transform(
    scaled_observations[['VALUE_NUMERIC']]
    )   
    return scaled_observations

In [96]:
def create_numeric_column(observations):

    processed_observations = observations.copy()

    processed_observations['VALUE_NUMERIC'] = pd.to_numeric(
        processed_observations['VALUE'],
        errors='coerce'
    )

    processed_observations = processed_observations.dropna(
        subset=['VALUE_NUMERIC']
    )

    return processed_observations

In [97]:
sd = scale_data(numeric_observations)
sd.head()

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE,VALUE_NUMERIC,IF_Outlier
0,2016-09-14T14:14:37Z,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-1ec6-f421cd754275,vital-signs,8310-5,Body temperature,37.2,Cel,numeric,-0.087516,1
1,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,8302-2,Body Height,144.8,cm,numeric,-0.084517,1
2,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,4,{score},numeric,-0.088441,1
3,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,29463-7,Body Weight,40.2,kg,numeric,-0.087432,1
4,2016-12-18T18:43:43Z,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,ca4f2fef-0fea-5cdb-8256-7d69c050f533,vital-signs,39156-5,Body mass index (BMI) [Ratio],19.2,kg/m2,numeric,-0.088017,1

In [98]:
#pipelines creation
pipeline1 = {
    'missing_method':'mode',
    'outlier_method':'keep',
    'scaler':'standard'
}

In [99]:
pipeline2 = {
    'missing_method':'mode',
    'outlier_method':'keep',
    'scaler':'robust'
}

In [100]:
pipeline3 = {
    'missing_method':'constant',
    'outlier_method':'iqr',
    'scaler':'standard'
}

In [101]:
pipelines = []
pipelines.append(pipeline1)
pipelines.append(pipeline2)
pipelines.append(pipeline3)

In [102]:
pipelines

[{'missing_method': 'mode', 'outlier_method': 'keep', 'scaler': 'standard'},
 {'missing_method': 'mode', 'outlier_method': 'keep', 'scaler': 'robust'},
 {'missing_method': 'constant', 'outlier_method': 'iqr', 'scaler': 'standard'}]

In [103]:
def apply_mode_imputation(observations):

    processed_observations = observations.copy()

    missing_cols = ['ENCOUNTER','CATEGORY','UNITS']

    mode_imputer = SimpleImputer(strategy='most_frequent')

    processed_observations[missing_cols] = mode_imputer.fit_transform(
        processed_observations[missing_cols]
    )

    return processed_observations

In [104]:
def apply_constant_imputation(observations):

    processed_observations = observations.copy()

    missing_cols = ['ENCOUNTER','CATEGORY','UNITS']

    constant_imputer = SimpleImputer(
        strategy='constant',
        fill_value='Unknown'
    )

    processed_observations[missing_cols] = constant_imputer.fit_transform(
        processed_observations[missing_cols]
    )

    return processed_observations

In [105]:
def apply_keep_outliers(observations):

    return observations.copy()

In [106]:
def apply_iqr_outliers(observations):

    processed_observations = observations.copy()

    col = 'VALUE_NUMERIC'

    Q1 = processed_observations[col].quantile(0.25)

    Q3 = processed_observations[col].quantile(0.75)

    IQR = Q3-Q1

    lower = Q1-1.5*IQR

    upper = Q3+1.5*IQR

    processed_observations = processed_observations[
        (processed_observations[col]>=lower)
        &
        (processed_observations[col]<=upper)
    ]

    return processed_observations

In [107]:
def create_numeric_column(observations):

    processed_observations = observations.copy()

    processed_observations['VALUE_NUMERIC'] = pd.to_numeric(

        processed_observations['VALUE'],

        errors='coerce'

    )

    processed_observations.dropna(

        subset=['VALUE_NUMERIC'],

        inplace=True

    )

    return processed_observations

In [108]:
def apply_pipeline(observations,pipeline):

    processed_observations = observations.copy()
    if pipeline['missing_method']=='mode':

        processed_observations = apply_mode_imputation(
            processed_observations
        )

    elif pipeline['missing_method']=='constant':

        processed_observations = apply_constant_imputation(
            processed_observations
        )

        #outlier engine

    if pipeline['outlier_method']=='keep':

        processed_observations = apply_keep_outliers(
            processed_observations
        )

    elif pipeline['outlier_method']=='iqr':

        processed_observations = apply_iqr_outliers(
            processed_observations
        ) 

    processed_observations = create_numeric_column(
    processed_observations
)   
    print(processed_observations.columns)


    #scalling Engine
    processed_observations = scale_data(

        processed_observations,

        method=pipeline['scaler']

    )
    
#return  Final DataSet
    return processed_observations

In [109]:

# Pipeline Definitions

pipeline1 = {

    'missing_method': 'mode',

    'outlier_method': 'keep',

    'scaler': 'standard'

}

pipeline2 = {

    'missing_method': 'mode',

    'outlier_method': 'keep',

    'scaler': 'robust'
    
}

In [110]:

# pipeline3 = {

#     'missing_method': 'constant',

#     'outlier_method': 'iqr',

#     'scaler': 'standard'

# }

In [116]:
cleaned_observations_1 = apply_pipeline(
    observations,
    pipeline1
)

cleaned_observations_2 = apply_pipeline(
    observations,
    pipeline2
)

# cleaned_observations_3 = apply_pipeline(
#     observations,
#     pipeline3
# )

# cleaned_observations_1.head()

# cleaned_observations_2.head()

# cleaned_observations_3.head()

Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION',
       'VALUE', 'UNITS', 'TYPE', 'VALUE_NUMERIC'],
      dtype='str')
Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION',
       'VALUE', 'UNITS', 'TYPE', 'VALUE_NUMERIC'],
      dtype='str')

In [112]:
test = create_numeric_column(observations)

print(test.columns)

Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION',
       'VALUE', 'UNITS', 'TYPE', 'VALUE_NUMERIC'],
      dtype='str')

In [113]:
test[['VALUE','VALUE_NUMERIC']].head()

   VALUE  VALUE_NUMERIC
0   37.2           37.2
1  144.8          144.8
2      4            4.0
3   40.2           40.2
4   19.2           19.2

In [114]:
#Pipeline Evaluation Engine
def evaluate_pipeline(observations):
    score = {}
    score ['rows'] = observations.shape[0]
    score ['columns'] = observations.shape[1]

    score['missing_values'] = observations.isnull().sum().sum()

    score['duplicates'] = observations.duplicated().sum()

    return score

In [ ]:
score1 = evaluate_pipeline(cleaned_observations_1)
score1

{'rows': 43351,
 'columns': 10,
 'missing_values': np.int64(0),
 'duplicates': np.int64(7)}